const bookDetailsOldViz = {
    bookOldViz1: {
      title: 'Uzumaki: Spiral into Horror, Vol. 1',
      description: "",
      format: 'HARDCOVER',
      publicationDate: 'October 6, 2001',
      isbn: 'ISBN-10: 1569317143',
      image: '',
      color: '#D0282F',
    },
    bookOldViz2: {
      title: 'Uzumaki: Spiral into Horror, Vol. 2',
      description: "",
      format: 'HARDCOVER',
      publicationDate: 'July 6, 2002',
      isbn: 'ISBN-10: 1591160332',
      image: '',
      color: '#D0282F',
    },
    bookOldViz3: {
      title: 'Uzumaki: Spiral into Horror, Vol. 3',
      description: "",
      format: 'HARDCOVER',
      publicationDate: 'October 6, 2002',
      isbn: 'ISBN-10: 1591160480',
      image: '',
      color: '#D0282F',
    },
    bookOldViz4: {
      title: 'Uzumaki: Spiral into Horror, Vol. 1 - 2nd Edition',
      description: "",
      format: 'HARDCOVER',
      publicationDate: 'October 16, 2007',
      isbn: 'ISBN-10: 1421513897',
      image: '',
      color: '#D0282F',
    },
    bookOldViz5: {
      title: 'Uzumaki: Spiral into Horror, Vol. 2 - 2nd Edition',
      description: "",
      format: 'HARDCOVER',
      publicationDate: 'December 18, 2007',
      isbn: 'ISBN-10: 1421513900',
      image: '',
      color: '#D0282F',
    },
    bookOldViz6: {
      title: 'Uzumaki: Spiral into Horror, Vol. 3 - 2nd Edition',
      description: "",
      format: 'HARDCOVER',
      publicationDate: 'February 12, 2008',
      isbn: 'ISBN-10: 1421513919',
      image: '',
      color: '#D0282F',
    },
    bookOldViz7: {
      title: 'Gyo, Vol. 1',
      description: "",
      format: 'HARDCOVER',
      publicationDate: 'September 10, 2003',
      isbn: 'ISBN-10: 8417777806',
      image: '',
      color: '#D0282F',
    },
    bookOldViz8: {
      title: 'Gyo, Vol. 2',
      description: "",
      format: 'HARDCOVER',
      publicationDate: 'March 10, 2004',
      isbn: 'ISBN-10: 1591161401',
      image: '',
      color: '#D0282F',
    },
    bookOldViz9: {
      title: 'Gyo, Vol. 1 - 2nd Edition',
      description: "",
      format: 'HARDCOVER',
      publicationDate: 'October 16, 2007',
      isbn: 'ISBN-10: 1421513870',
      image: '',
      color: '#D0282F',
    },
    bookOldViz10: {
      title: 'Gyo, Vol. 2 - 2nd Edition',
      description: "",
      format: 'HARDCOVER',
      publicationDate: 'January 2008',
      isbn: 'ISBN-10: 1421513889',
      image: '',
      color: '#D0282F',
    },
  };
  export default bookDetailsOldViz;
  